In [221]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## 시드고정

In [222]:
import random
import os
import numpy as np
import torch
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

seed_everything(41) # Seed 고정

## Import

In [223]:
import pandas as pd
import seaborn as sns
import numpy as np

from sklearn import svm
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.decomposition import PCA

import random
import os
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import seaborn as sns

from sklearn.preprocessing import Normalizer
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import torch.utils.data as data_utils
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import sklearn
import sklearn.preprocessing as sp
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.manifold import TSNE

from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

# EllipticEnvelope

In [224]:
train_df = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/train.csv')
val_df = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/val.csv')
test = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/test.csv')

print(train_df.shape, val_df.shape, test.shape)

(113842, 31) (28462, 32) (142503, 31)


In [225]:
from sklearn import svm
from sklearn.datasets import make_moons, make_blobs
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.linear_model import SGDOneClassSVM
from sklearn.kernel_approximation import Nystroem
from sklearn.pipeline import make_pipeline

In [226]:
from sklearn.metrics import f1_score, confusion_matrix, classification_report, precision_recall_fscore_support
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import EllipticEnvelope

In [227]:
# Train dataset은 Label이 존재하지 않음
train_df = train_df.drop(columns=['ID']) # Input Data

In [228]:
from sklearn.preprocessing import StandardScaler
# StandardScaler 선언 및 Fitting
sdscaler = StandardScaler()
sdscaler.fit(train_df)

# 데이터 변환
sdscaled_data = sdscaler.transform(train_df)

# 데이터 프레임으로 저장
sdscaled_data = pd.DataFrame(sdscaled_data)

In [229]:
sdscaled_data

0         1         2         3         4         5         6   \
0      -0.696317 -0.812481  1.178089  0.271798 -0.368309  1.349308  0.652511   
1      -0.495358 -0.112967  1.191305 -0.608173 -0.007886  0.933476  0.192541   
2      -0.218427  0.580982  0.755819 -0.116154  0.307498 -0.026206  0.390690   
3      -0.330318  0.858041  0.711241 -0.345477  0.693558  0.317890  0.925884   
4      -0.458462  0.172537 -0.082109 -0.189262  1.951788  2.793282  0.302611   
...          ...       ...       ...       ...       ...       ...       ...   
113837 -6.415477  6.169704 -5.669274 -1.774215 -3.354334 -1.051879 -3.021567   
113838  0.965967 -0.087719 -0.674497  1.069597 -0.026160 -0.465046  0.153202   
113839 -0.124097  0.430608  0.260596 -0.325094  0.178465 -1.013702  0.767042   
113840  0.061566  0.563104 -0.371251 -0.524503  0.826191 -0.181210  0.670168   
113841 -6.089697  6.099426 -6.576552 -1.460036 -3.923101 -1.963042 -4.089330   

              7         8         9   ...        20        21        22  \
0       0.210988 -1.380804  0.188955  ...  0.345210  1.066111  1.431834   
1       0.320444 -1.264291 -0.056156  ... -0.148280  0.007285 -0.297148   
2       0.221649 -0.517216 -0.351540  ... -0.286720 -0.773425 -0.039431   
3      -3.209968  0.563699  1.161326  ...  2.693508 -1.402900  0.092477   
4       0.719980 -0.355977 -0.387965  ... -0.099976 -0.370382 -0.319020   
...          ...       ...       ...  ...       ...       ...       ...   
113837  4.640268  4.468824  8.074160  ... -1.306812 -2.162159  1.402375   
113838 -0.208020  0.610333  0.107995  ...  0.201179  0.876793 -0.064140   
113839 -0.171877  0.098905 -0.270613  ... -0.315282 -0.710635  0.441651   
113840  0.099151 -0.184366 -0.618512  ... -0.433467 -1.117010  0.081219   
113841  6.164311  1.749605  4.061261  ...  0.297364  0.154545  1.597020   

              23        24        25        26        27        28        29  
0      -1.136246 -0.633230 -0.288586 -0.137969 -0.166355  1.188563 -1.990839  
1      -1.938909  1.241563 -0.460803  0.157587  0.173998  0.143876 -1.990839  
2      -0.611606 -0.450853  0.220818  0.635984  0.229098 -0.346737 -1.990818  
3      -1.070930 -0.801717 -0.106743 -3.020466 -3.046182 -0.194717 -1.990712  
4       1.671161  0.714378 -0.798093  0.029990  0.401295  0.019821 -1.990712  
...          ...       ...       ...       ...       ...       ...       ...  
113837 -2.067159  3.432320  0.667510  5.233857  3.463283 -0.321352  1.645815  
113838 -0.086360  0.605158 -0.958774  0.046304 -0.113892 -0.116108  1.645857  
113839  0.614549 -1.078550  0.235849  0.329761  0.229617 -0.339285  1.645899  
113840  0.171137 -0.841334  0.258583  0.546111  0.194625 -0.350749  1.645962  
113841 -0.839255  2.759503  0.520457  2.362643  2.314445 -0.358610  1.645983  

[113842 rows x 30 columns]

In [230]:
def get_pred_label(model_pred):
    # IsolationForest 모델 출력 (1:정상, -1:불량(사기)) 이므로 (0:정상, 1:불량(사기))로 Label 변환
    model_pred = np.where(model_pred == 1, 0, model_pred)
    model_pred = np.where(model_pred == -1, 1, model_pred)
    return model_pred

In [231]:
val_x = val_df.drop(columns=['ID', 'Class']) # Input Data

In [232]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 선언 및 Fitting
StandardScaler = StandardScaler()
StandardScaler.fit(val_x)

# 데이터 변환
val_StandardScaled_data = StandardScaler.transform(val_x)

# 데이터 프레임으로 저장
val_StandardScaled_data = pd.DataFrame(val_StandardScaled_data)

## model define, fit

In [233]:
model = EllipticEnvelope(support_fraction = 0.994, contamination = 0.00112, random_state = 42)
model.fit(sdscaled_data)
val_y = val_df['Class'] # Label

val_pred_E = model.predict(val_StandardScaled_data) # model prediction
val_pred_E = get_pred_label(val_pred_E)
val_score_E = f1_score(val_y, val_pred_E, average='macro')
print(f'Validation F1 Score : [{val_score_E}]')
print(classification_report(val_y, val_pred_E))

Validation F1 Score : [0.9236496787663914]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28432
           1       0.86      0.83      0.85        30

    accuracy                           1.00     28462
   macro avg       0.93      0.92      0.92     28462
weighted avg       1.00      1.00      1.00     28462



In [234]:
val_pred_E

array([0, 0, 0, ..., 0, 0, 0])

## test

In [235]:
test_x = test.drop(columns=['ID'])

In [236]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 선언 및 Fitting
StandardScaler = StandardScaler()
StandardScaler.fit(test_x)

# 데이터 변환
test_StandardScaled_data = StandardScaler.transform(test_x)

# 데이터 프레임으로 저장
test_StandardScaled_data = pd.DataFrame(test_StandardScaled_data)

In [237]:
#best model : model "EllipticEnvelope"
test_pred_E = model.predict(test_StandardScaled_data) # model prediction
test_pred_E = get_pred_label(test_pred_E)

In [238]:
test_pred_E

array([0, 0, 0, ..., 0, 0, 0])

In [239]:
len(test_pred_E)

142503

# Isolation Forest

In [240]:
isf13 = IsolationForest(n_estimators=200, max_samples = 0.2, contamination=0.0011, max_features=1.0, random_state=0).fit(train_df.loc[:, ['V17', 'V14', 'V12', 'V10', 'V7', 'V3', 'V16']])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


In [241]:
result13 = isf13.predict(val_x.loc[:, ['V17', 'V14', 'V12', 'V10', 'V7', 'V3', 'V16']])

In [242]:
val_score_I = f1_score(val_y, np.where(result13==1, 0, 1), average='macro')
val_score_I

0.7879157743510873

In [243]:
val_pred_I = np.where(result13==1, 0, 1)

In [244]:
val_pred_I

array([0, 0, 0, ..., 0, 0, 0])

In [245]:
test_pred_I = isf13.predict(test_x.loc[:, ['V17', 'V14', 'V12', 'V10', 'V7', 'V3', 'V16']])

In [246]:
test_pred_I = np.where(test_pred_I==1, 0, 1)
test_pred_I

array([0, 0, 0, ..., 0, 0, 0])

In [247]:
len(test_pred_I)

142503

---

# One-Class SVM

In [248]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [249]:
def get_pred_label(model, x, k):
  prob = model.score_samples(x)
  prob = torch.tensor(prob, dtype = torch.float)
  topk_indices = torch.topk(prob, k = k, largest = False).indices

  pred = torch.zeros(len(x), dtype = torch.long)
  pred[topk_indices] = 1
  return pred.tolist(), prob.tolist()

In [250]:
train_df = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/train.csv').drop(columns=['ID'])
valid_df = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/val.csv').drop(columns=['ID'])

In [251]:
std_scaler = StandardScaler()
train_std = std_scaler.fit_transform(train_df)

pca = PCA(n_components=3)
prcomponent = pca.fit_transform(train_std)

In [252]:
principal = pd.DataFrame(data=prcomponent, columns = ['pca_v1', 'pca_v2', 'pca_v3'])

In [253]:
model = svm.OneClassSVM(gamma=0.0001, kernel='rbf', max_iter=100000, nu=0.001, verbose=True)
model.fit(principal)

[LibSVM]

OneClassSVM(gamma=0.0001, max_iter=100000, nu=0.001, verbose=True)

In [254]:
valid_std = std_scaler.fit_transform(valid_df)
prcomponent_ = pca.fit_transform(valid_std)
principal_ = pd.DataFrame(data=prcomponent_, columns = ['pca_v1', 'pca_v2', 'pca_v3'])

In [255]:
lab = valid_df.iloc[:,-1]

In [256]:
val_pred_O, val_prob_O = get_pred_label(model, principal_, 28)
val_score_O = f1_score(lab, val_pred_O, average='macro')
print(f'Validation F1 Score : [{val_score_O}]')
print(classification_report(lab, val_pred_O))
tn, fp, fn, tp = confusion_matrix(lab, val_pred_O).ravel()
print('tp : ', tp, ', fp : ', fp, ', tn : ', tn, ', fn : ', fn)

Validation F1 Score : [0.9137051774467988]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28432
           1       0.86      0.80      0.83        30

    accuracy                           1.00     28462
   macro avg       0.93      0.90      0.91     28462
weighted avg       1.00      1.00      1.00     28462

tp :  24 , fp :  4 , tn :  28428 , fn :  6


In [257]:
val_pred_O = np.array(val_pred_O)

In [258]:
def get_pred_label_(model_pred):
    model_pred = np.where(model_pred == 1, 0, model_pred)
    model_pred = np.where(model_pred == -1, 1, model_pred)
    return model_pred

In [259]:
col_t = test_x.columns
test_df_std = std_scaler.fit_transform(test_x)
test_df_std_ = pd.DataFrame(data=test_df_std, columns=col_t)

prcomponent_ = pca.fit_transform(test_df_std_)
principal_ = pd.DataFrame(data=prcomponent_, columns = ['pca_v1', 'pca_v2', 'pca_v3'])

test_pred_O = model.predict(principal_)
test_pred_O = get_pred_label_(test_pred_O)

In [260]:
test_pred_O

array([0, 0, 0, ..., 0, 0, 0])

# Auto Encoder

In [261]:
from torch.utils.data import Dataset, DataLoader
from tqdm.auto import tqdm
from sklearn.metrics import f1_score
import os

In [262]:
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
device

device(type='cpu')

In [263]:
print(type(device))

<class 'torch.device'>


In [264]:
EPOCHS = 400
LR = 1e-2
BS = 16384
SEED = 41

In [265]:
train_df = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/train.csv').drop(columns=['ID'])
valid_df = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/val.csv').drop(columns=['ID'])

In [266]:
class MyDataset(Dataset):
    def __init__(self, df, eval_mode):
        self.df = df
        self.eval_mode = eval_mode
        if self.eval_mode:
            self.labels = self.df['Class'].values
            self.df = self.df.drop(columns=['Class']).values
        else:
            self.df = self.df.values
        
    def __getitem__(self, index):
        if self.eval_mode:
            self.x = self.df[index]
            self.y = self.labels[index]
            return torch.Tensor(self.x), self.y
        else:
            self.x = self.df[index]
            return torch.Tensor(self.x)
        
    def __len__(self):
        return len(self.df)

In [267]:
train_dataset = MyDataset(df=train_df, eval_mode=False)
train_loader = DataLoader(train_dataset, batch_size=BS, shuffle=True, num_workers=2)

val_dataset = MyDataset(df = valid_df, eval_mode=True)
val_loader = DataLoader(val_dataset, batch_size=BS, shuffle=False, num_workers=2)

In [268]:
class AutoEncoder(nn.Module):
    def __init__(self):
        super(AutoEncoder, self).__init__()
        self.Encoder = nn.Sequential(
            nn.Linear(30,64),
            nn.BatchNorm1d(64),
            nn.GELU(),
            nn.Linear(64,128),
            nn.BatchNorm1d(128),
            nn.GELU(),
        )
        self.Decoder = nn.Sequential(
            nn.Linear(128,64),
            nn.BatchNorm1d(64),
            nn.GELU(),
            nn.Linear(64,30),
        )
        
    def forward(self, x):
        x = self.Encoder(x)
        x = self.Decoder(x)
        return x

In [270]:
class Trainer():
    def __init__(self, model, optimizer, train_loader, val_loader, scheduler, device):
        self.model = model
        self.optimizer = optimizer
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.scheduler = scheduler
        self.device = device
        # Loss Function
        self.criterion = nn.L1Loss().to(self.device)
        
    def fit(self, ):
        self.model.to(self.device)
        best_score = 0
        for epoch in range(EPOCHS):
            self.model.train()
            train_loss = []
            for x in iter(self.train_loader):
                x = x.float().to(self.device)
                self.optimizer.zero_grad()

                _x = self.model(x)
                loss = self.criterion(x, _x)

                loss.backward()
                self.optimizer.step()

                train_loss.append(loss.item())

            score = self.validation(self.model, 0.95)
            print(f'Epoch : [{epoch}] Train loss : [{np.mean(train_loss)}] Val Score : [{score}])')

            if self.scheduler is not None:
                self.scheduler.step(score)

            if best_score < score:
                best_score = score
                torch.save(model.module.state_dict(), './drive/MyDrive/신용카드 사기 데이콘/best_model.pth', _use_new_zipfile_serialization=False)
    
    def validation(self, eval_model, thr):
        cos = nn.CosineSimilarity(dim=1, eps=1e-6)
        eval_model.eval()
        pred = []
        true = []
        with torch.no_grad():
            for x, y in iter(self.val_loader):
                x = x.float().to(self.device)

                _x = self.model(x)
                diff = cos(x, _x).cpu().tolist()
                batch_pred = np.where(np.array(diff)<thr, 1,0).tolist()
                pred += batch_pred
                true += y.tolist()

        return f1_score(true, pred, average='macro')
        
    def test(self, test_loader):
        cos = nn.CosineSimilarity(dim=1, eps=1e-6)
        self.model.eval()
        pred = []
        pred_A = []  # initialize list to store test predictions
        with torch.no_grad():
            for x in test_loader:
                # x: (batch size, 30)
                x = x.float().to(self.device)
                _x = self.model(x)
                diff = cos(x, _x).cpu().tolist()
                batch_pred = np.where(np.array(diff) < self.thr, 0, 1).tolist()
                pred += batch_pred
                pred_A += diff  # add test predictions to list
        return pred, pred_A


In [271]:
model = nn.DataParallel(AutoEncoder())
model.eval()
optimizer = torch.optim.Adam(params = model.parameters(), lr = LR)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=10, threshold_mode='abs', min_lr=1e-8, verbose=True)

trainer = Trainer(model, optimizer, train_loader, val_loader, scheduler, device)
trainer.fit()

Epoch : [0] Train loss : [0.5294157692364284] Val Score : [0.009328527964631291])
Epoch : [1] Train loss : [0.3421591946056911] Val Score : [0.19926182594361966])
Epoch : [2] Train loss : [0.2526163841996874] Val Score : [0.3622378080337761])
Epoch : [3] Train loss : [0.20023635029792786] Val Score : [0.43067686434521035])
Epoch : [4] Train loss : [0.16755458073956625] Val Score : [0.468002072256841])
Epoch : [5] Train loss : [0.14628484206540243] Val Score : [0.48657508769301583])
Epoch : [6] Train loss : [0.13157634224210465] Val Score : [0.49477559776715424])
Epoch : [7] Train loss : [0.1223030611872673] Val Score : [0.498118180580976])
Epoch : [8] Train loss : [0.11527829191514424] Val Score : [0.5012190092285378])
Epoch : [9] Train loss : [0.1108942979148456] Val Score : [0.5035856909160894])
Epoch : [10] Train loss : [0.10588656472308296] Val Score : [0.5060319599789475])
Epoch : [11] Train loss : [0.10174568210329328] Val Score : [0.5080426247561235])
Epoch : [12] Train loss : [

In [272]:
model = AutoEncoder()
model.load_state_dict(torch.load('./drive/MyDrive/신용카드 사기 데이콘/best_model.pth'))
model = nn.DataParallel(model)
model.eval()

DataParallel(
  (module): AutoEncoder(
    (Encoder): Sequential(
      (0): Linear(in_features=30, out_features=64, bias=True)
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): GELU(approximate='none')
      (3): Linear(in_features=64, out_features=128, bias=True)
      (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): GELU(approximate='none')
    )
    (Decoder): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): GELU(approximate='none')
      (3): Linear(in_features=64, out_features=30, bias=True)
    )
  )
)

In [273]:
valid_dff = valid_df.drop(columns=['Class'])

In [274]:
va_dataset = MyDataset(valid_dff, False)
va_loader = DataLoader(va_dataset, batch_size=BS, shuffle=False, num_workers=6)

/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 6 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(


In [275]:
def prediction(model, thr, test_loader, device):
    model.to(device)
    model.eval()
    cos = nn.CosineSimilarity(dim=1, eps=1e-6)
    pred = []
    with torch.no_grad():
        for x in iter(test_loader):
            x = x.float().to(device)
            
            _x = model(x)
            
            diff = cos(x, _x).cpu().tolist()
            batch_pred = np.where(np.array(diff)<thr, 1,0).tolist()
            pred += batch_pred
    return pred

In [276]:
val_pred_A = prediction(model, 0.95, va_loader, device)

In [277]:
val_pred_A

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [278]:
val_pred_A = np.array(val_pred_A).reshape(-1)

In [279]:
val_pred_A

array([0, 0, 0, ..., 0, 0, 0])

In [280]:
test = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/test.csv')
test = test.drop(columns=['ID'])

In [281]:
test_dataset = MyDataset(test, False)
test_loader = DataLoader(test_dataset, batch_size=BS, shuffle=False, num_workers=6)

In [282]:
def prediction(model, thr, test_loader, device):
    model.to(device)
    model.eval()
    cos = nn.CosineSimilarity(dim=1, eps=1e-6)
    pred = []
    with torch.no_grad():
        for x in iter(test_loader):
            x = x.float().to(device)
            _x = model(x)
            
            diff = cos(x, _x).cpu().tolist()
            batch_pred = np.where(np.array(diff)<thr, 1,0).tolist()
            pred += batch_pred
    return pred

In [283]:
preds = prediction(model, 0.95, test_loader, device)

In [284]:
preds

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [285]:
test_pred_A = np.array(preds).reshape(-1)

In [286]:
test_pred_A

array([0, 0, 0, ..., 0, 0, 0])

# ENSEMBLE

EIO HardVoting

In [287]:
from sklearn.metrics import f1_score

# Hard voting ensemble
ensemble_pred = (val_pred_O + val_pred_I + val_pred_E) >= 2
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (hard voting): {ensemble_score}')

Ensemble F1 Score (hard voting): 0.9137051774467988


In [288]:
from sklearn.metrics import f1_score

# Hard voting ensemble
test_ensemble_pred = (test_pred_O + test_pred_I + test_pred_E) >= 2
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/EIO_hard.csv', index=False)

EIA HardVoting

In [289]:
from sklearn.metrics import f1_score

# Hard voting ensemble
ensemble_pred = (val_pred_A + val_pred_I + val_pred_E) >= 2
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (hard voting): {ensemble_score}')

Ensemble F1 Score (hard voting): 0.9236496787663914


In [290]:
from sklearn.metrics import f1_score

# Hard voting ensemble
test_ensemble_pred = (test_pred_A + test_pred_I + test_pred_E) >= 2
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/EIA_hard.csv', index=False)

EOA HardVoting

In [291]:
from sklearn.metrics import f1_score

# Hard voting ensemble
ensemble_pred = (val_pred_A + val_pred_O + val_pred_E) >= 2
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (hard voting): {ensemble_score}')

Ensemble F1 Score (hard voting): 0.9236496787663914


In [292]:
from sklearn.metrics import f1_score

# Hard voting ensemble
test_ensemble_pred = (test_pred_O + test_pred_A + test_pred_E) >= 2
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/EOA_hard.csv', index=False)

IOA HardVoting

In [293]:
from sklearn.metrics import f1_score

# Hard voting ensemble
ensemble_pred = (val_pred_A + val_pred_O + val_pred_I) >= 2
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (hard voting): {ensemble_score}')

Ensemble F1 Score (hard voting): 0.9137051774467988


In [294]:
from sklearn.metrics import f1_score

# Hard voting ensemble
test_ensemble_pred = (test_pred_O + test_pred_A + test_pred_I) >= 2
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/IOA_hard.csv', index=False)

# ENSEMBLE (Soft Voting)

EIO SoftVoting

In [295]:
import numpy as np
from sklearn.metrics import f1_score

# Soft voting ensemble
ensemble_pred = np.round((val_pred_O + val_pred_I + val_pred_E) / 3)
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (soft voting): {ensemble_score}')

Ensemble F1 Score (soft voting): 0.9137051774467988


In [296]:
from sklearn.metrics import f1_score

# Soft voting ensemble
test_ensemble_pred = np.round((test_pred_O + test_pred_E + test_pred_I) / 3)
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/EIO_soft.csv', index=False)

EIA SoftVoting

In [297]:
import numpy as np
from sklearn.metrics import f1_score

# Soft voting ensemble
ensemble_pred = np.round((val_pred_A + val_pred_I + val_pred_E) / 3)
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (soft voting): {ensemble_score}')

Ensemble F1 Score (soft voting): 0.9236496787663914


In [298]:
from sklearn.metrics import f1_score

# Soft voting ensemble
test_ensemble_pred = np.round((test_pred_A + test_pred_E + test_pred_I) / 3)
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/EIA_soft.csv', index=False)

EOA SoftVoting

In [299]:
import numpy as np
from sklearn.metrics import f1_score

# Soft voting ensemble
ensemble_pred = np.round((val_pred_A + val_pred_O + val_pred_E) / 3)
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (soft voting): {ensemble_score}')

Ensemble F1 Score (soft voting): 0.9236496787663914


In [300]:
from sklearn.metrics import f1_score

# Soft voting ensemble
test_ensemble_pred = np.round((test_pred_A + test_pred_E + test_pred_O) / 3)
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/EOA_soft.csv', index=False)

IOA Soft Voting

In [301]:
import numpy as np
from sklearn.metrics import f1_score

# Soft voting ensemble
ensemble_pred = np.round((val_pred_A + val_pred_O + val_pred_I) / 3)
ensemble_score = f1_score(val_y, ensemble_pred, average='macro')
print(f'Ensemble F1 Score (soft voting): {ensemble_score}')

Ensemble F1 Score (soft voting): 0.9137051774467988


In [302]:
from sklearn.metrics import f1_score

# Soft voting ensemble
test_ensemble_pred = np.round((test_pred_A + test_pred_O + test_pred_I) / 3)
ensemble_pred_int = test_ensemble_pred.astype(int)
submit = pd.read_csv('./drive/MyDrive/신용카드 사기 데이콘/open/sample_submission.csv')
submit['Class'] = ensemble_pred_int
submit.to_csv('./drive/MyDrive/신용카드 사기 데이콘/open/IOA_soft.csv', index=False)